# Generated by Django 4.1.4 on 2023-02-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AvailableUnits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Listings',
        ),
    ]
