# Generated by Django 4.1.4 on 2023-02-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvailableUnits', '0002_rename_post_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
